version: '3.7'
services:
  php8-sf6:
    container_name: php8-sf6
    build: .docker/php8-sf6
    ports:
      - "9000:8000"
    volumes:
      - ./backend:/var/www/html

  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432"

volumes:
  db-data: