name: PHP Composer
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate composer.json and composer.lock
      run: | 
          cd backend/livre-hero-back
          composer update
          composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: |
        cd backend/livre-hero-back
        composer install --prefer-dist --no-progress

    - name: Create Database
      run: |
        cd backend/livre-hero-back
        mkdir -p data
        touch data/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite
      run: |
        backend/livre-hero-back/bin/phpunit backend/livre-hero-back/tests/
    - name: PHPStan Static Analysis
      uses: php-actions/phpstan@v2
      with:
        configuration: backend/livre-hero-back/phpstan.neon
        memory_limit: 256M
